Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  $install_tools = <<-SCRIPT
    echo "Atualizando pacotes e instalando essenciais..."
    sudo apt-get update -y
    sudo apt-get install -y curl git unzip
    
    echo "Instalando Docker..."
    sudo apt-get install -y docker.io docker-compose
    sudo usermod -aG docker vagrant
    sudo systemctl enable docker
    sudo systemctl start docker
  SCRIPT

 
  (1..3).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.hostname = "node-#{i}"
      
      node.vm.network "private_network", ip: "192.168.56.#{10 + i}"

      node.vm.provider "virtualbox" do |vb|
        vb.name = "aponti-maquina-dev-#{i}"
        vb.memory = "2048"
        vb.cpus = 2
      end

      node.vm.provision "shell", inline: $install_tools
    end
  end
end